version: '3.1'

services:
    # Grafana Service
    grafana:
        image: grafana/grafana:6.5.0
        container_name: grafana
        restart: unless-stopped
        ports:
            - 3000:3000
        env_file:
            - ./Grafana/login_config
        volumes:
            - ./Grafana/grafana_db:/var/lib/grafana:rw 
            - ./Grafana/provisioning/datasource:/etc/grafana/provisioning/datasources
            - ./Grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards 
        depends_on:
            - prometheus
    
    # Prometheus Service   
    prometheus:
        image: prom/prometheus:v2.20.1
        container_name: prometheus
        restart: unless-stopped
        ports: 
            - 9090:9090
        expose:
            - 9090
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        volumes:
            - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - ./Prometheus/prometheus_db:/prometheus/data:rw
