# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor:  'Spark-monitoring'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  # - 'prometheus.yml'
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

##############
# Prometheus #  
##############
  - job_name: 'prometheus'
    scrape_interval: 10s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090'] 
    
###############
# Node-exporter #  
###############
  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          group:  'spark'
          instance: 'node-exporter'

###############
# Spark Master #  
###############
  - job_name: 'spark-master'
    scrape_interval: 10s
    metrics_path: '/metrics/master/prometheus'
    static_configs:
      - targets: ['spark:8080']
        labels:
          group:  'spark'
          instance: 'master'

###############
# Spark Worker #  
###############
  - job_name: 'spark-worker'
    scrape_interval: 10s
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['spark:8081']
        labels:
          group:  'spark'
          instance: 'worker'

###############
# Spark Applications #  
###############
  - job_name: 'spark-applications'
    scrape_interval: 10s
    metrics_path: '/metrics/applications/prometheus'
    static_configs:
      - targets: ['spark:8080']
        labels:
          group:  'spark'
          instance: 'applications'

###############
# Spark Driver #  
###############
  - job_name: 'spark-driver'
    scrape_interval: 10s
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: ['spark:4040']
        labels:
          group:  'spark'
          instance: 'driver'