{
 "title": "Host Statistics",
 "description": "Basic host stats: CPU, Memory Usage, Disk Utilisation,  Filesystem usage, Temperature",
 "time": { "from": "2020-09-16T21:52:36.262Z", "to": "2020-09-16T22:02:36.262Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Machine",
    "query": "up{job=\"node-exporter\"}"
   },
   { "name": "job", "label": "job", "query": "node-exporter" }
  ]
 },
 "panels": [
  {
   "title": "Node Uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds{instance='node-exporter'} - node_boot_time_seconds{instance='node-exporter'}"
    }
   ]
  },
  {
   "title": "Node CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_cpu_cores{instance='node-exporter'}"
    }
   ]
  },
  {
   "title": "Node Free Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device='/dev/root',fstype='ext4',instance='node-exporter',mountpoint='/etc/hosts'}"
    }
   ]
  },
  {
   "title": "R1 Node Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance='robot1'}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance='node-exporter',mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance='node-exporter'} - node_memory_MemFree_bytes{instance='node-exporter'} - node_memory_Buffers_bytes{instance='node-exporter'} - node_memory_Cached_bytes{instance='node-exporter'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node-exporternode_memory_Buffers_bytes{instance='node-exporter'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance='node-exporter'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance='node-exporter'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance='robot1'}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance='node-exporter'}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance='node-exporter'}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Node Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_free_bytes{instance='node-exporter',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{instance='node-exporter'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}